version: '3.9'
services:
  db-accounts-transactions:
    container_name: db-accounts-transactions
    image: mongo
    hostname: host-bank
    restart: always
    ports:
      - "27023:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hrevilla
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - data-accounts-transactions:/data/db
    networks:
      - bank

volumes:
  data-accounts-transactions:
    name: data-accounts-transactions

networks:
  bank:
    name: bank